package biblioteca;

import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.util.Comparator;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mcfal
 */
public class RegistroUsuario extends javax.swing.JDialog {
    
    public static DefaultTableModel t;
    private TableRowSorter<DefaultTableModel> sorter;
    private VentPrincipal ventanaPrincipal;   
    
    public static int filaTabla;
   
    public RegistroUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ConectarBaseDatos();
        setTitle("Nuevo Usuario");
        setSize(575, 600);
        setLocationRelativeTo(null);      
       
        this.ventanaPrincipal = ventanaPrincipal;
      
    } 
    public void ConectarBaseDatos(){
        
         PrepararTabla();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tabla", "root", "");
            System.out.println("Conectado");
            
            String query = "SELECT * FROM usuario";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            
            t.setRowCount(0);
            
            while (rs.next()) {                
                String nombre = rs.getString("Nombre");
                String apellidos = rs.getString("Apellidos");                
                String dni = rs.getString("Dni");
                String telefono = rs.getString("Teléfono");                
                String idUsuario = rs.getString("IDUsuario");
                
                t.addRow(new Object[]{nombre, apellidos, dni, telefono, idUsuario});
            }
            rs.close();
            stmt.close();
            con.close();
            
        } catch (Exception ex) {
            System.out.println("No conectado. Error");
            ex.printStackTrace();
        }
        
    }
    void PrepararTabla(){       
        
        String titulos[] = {"Nombre", "Apellidos", "Dni", "Teléfono", "ID Usuario"};
        t = new DefaultTableModel(null, titulos);
        tablaUsuarios.doLayout();
        tablaUsuarios.setModel(t);
        tablaUsuarios.setDefaultEditor(Object.class, null);
        
        // Inicializar el TableRowSorter
        sorter = new TableRowSorter<>(t);
        tablaUsuarios.setRowSorter(sorter);
        
        // Definir el Comparator para la columna ID Usuario
        sorter.setComparator(4, new Comparator<String>() {
            @Override
            public int compare(String s1, String s2) {
                // Aquí se define la lógica de ordenamiento (teniendo en cuenta que son cadenas de texto).
                return Integer.parseInt(s1) - Integer.parseInt(s2);
            }
        });
    }
    
    // Método para actualizar el orden después de editar o añadir
    private void actualizarOrden() {
        sorter.setModel(t);
    }
    
    private String obtenerDNI(int fila) {
        return (String) t.getValueAt(fila, 2); 
    }

    RegistroUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public void msg(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Nuevo Usuario", JOptionPane.INFORMATION_MESSAGE);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtNombreUsuario = new java.awt.TextField();
        txtApellUsuario = new java.awt.TextField();
        txtDni = new java.awt.TextField();
        txtTelfono = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdUsuarioRegistro = new java.awt.TextField();
        buttonAñadir = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        buttonLimpiar = new javax.swing.JButton();
        buttonAceptar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));
        jDesktopPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTelfono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombre");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Apellidos");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Dni");
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Teléfono");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Id Usuario");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtIdUsuarioRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jDesktopPane1.setLayer(txtNombreUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtApellUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtDni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtTelfono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtIdUsuarioRegistro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(txtApellUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdUsuarioRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelfono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelfono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtIdUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 240));

        buttonAñadir.setText("Añadir");
        buttonAñadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        buttonEditar.setText("Editar");
        buttonEditar.setToolTipText("");
        buttonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tablaUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 530, 150));

        buttonLimpiar.setText("Limpiar Formulario");
        buttonLimpiar.setToolTipText("");
        buttonLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        buttonAceptar.setText("Aceptar");
        buttonAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        buttonEliminar.setText("Eliminar");
        buttonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    
    //AÑADIR USUARIO
    private void buttonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAñadirActionPerformed
        String nombre = txtNombreUsuario.getText();
        String apellidos = txtApellUsuario.getText();
        String dni = txtDni.getText();
        String telefono = txtTelfono.getText();       
        String idUsuario = txtIdUsuarioRegistro.getText();              
     
        t = (DefaultTableModel) tablaUsuarios.getModel();
        String filaUsuario[] = {nombre, apellidos, dni, telefono, idUsuario};     
        t.addRow(filaUsuario);        
        
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tabla", "root", "");
            System.out.println("Conectado");
            
            //Creo la sentencia SQL de insertar
            String insertQuery = "INSERT INTO usuario (Nombre, Apellidos, Dni, Teléfono, IDUsuario) VALUES (?, ?, ?, ?, ?)";
            
            //Preparo la sentencia
            PreparedStatement preparedStatement = con.prepareStatement(insertQuery);
            preparedStatement.setString(1, nombre);
            preparedStatement.setString(2, apellidos);            
            preparedStatement.setString(3, dni);
            preparedStatement.setString(4, telefono);            
            preparedStatement.setString(5, idUsuario);
            
            //Ejecuto la insercion
            int rowCount = preparedStatement.executeUpdate();
            
            //Cierra la conexion
            preparedStatement.close();
            con.close();
            
        } catch (Exception e) {
            System.out.println("No conectado. Error");
            e.printStackTrace();            
        }
        
        t.fireTableDataChanged();
        actualizarOrden();
    }//GEN-LAST:event_buttonAñadirActionPerformed

    //ELIMINAR USUARIO
    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed

        int fila = tablaUsuarios.getSelectedRow();        

        if (fila >= 0) {            
            String nombre = (String)t.getValueAt(fila, 0);
            t.removeRow(fila);
            
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tabla", "root", "");
                System.out.println("Conectado");
                
                //Creo sentencia de eliminacion SQL
                String deleteQuery = "DELETE FROM usuario WHERE Nombre = ?";                
                
                //Preparo la sentencia
                PreparedStatement preparedStatement = con.prepareStatement(deleteQuery);
                preparedStatement.setString(1, nombre);
                
                //Ejecuto la eliminación
                int rowCount = preparedStatement.executeUpdate();
                
                //cierro la conexion
                preparedStatement.close();
                con.close();                
                
            } catch (Exception e) {
                System.out.println("No conectado. Error");
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila");
        }        
        
        t.fireTableDataChanged();
        actualizarOrden();
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    //BOTON ACEPTAR
    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarActionPerformed
        //Limpio el formulario antes de salir
        limpiarFormulario();
        
        //Cierro el diálogo de registro de usuario
        this.dispose();

        //Regreso a la VentPrincipal y muestro el panel jPaneUsuarios
        if (ventanaPrincipal != null) {
            ventanaPrincipal.mostrarPanelUsuarios();
            buttonAceptar.setVisible(false);
        }
    }//GEN-LAST:event_buttonAceptarActionPerformed

    //BOTON EDITAR
    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
       
        VentPrincipal vp = new VentPrincipal();
        EditarRegistro jd = new EditarRegistro(vp, true);

        String[] datosActualizados = jd.obtenerDatosActualizados();
        
        jd.setVisible(true);

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tabla", "root", "");
            System.out.println("Conectado");

            //Creo sentencia de eliminacion SQL
            String insertQuery = "UPDATE usuario SET Nombre = ?, Apellidos = ?, Dni = ?, Teléfono = ? WHERE IDUsuario = ?";
            
            //Preparo la sentencia
            PreparedStatement preparedStatement = con.prepareStatement(insertQuery);
            preparedStatement.setString(1, datosActualizados[0]);
            preparedStatement.setString(2, datosActualizados[1]);
            preparedStatement.setString(3, datosActualizados[2]);
            preparedStatement.setString(4, datosActualizados[3]);
            preparedStatement.setString(5, datosActualizados[4]);
            
            //Ejecuto la inserción
            int rowCount = preparedStatement.executeUpdate();
            
            //Cierro la conexion
            preparedStatement.close();
            con.close();   
        } catch (Exception e) {
            System.out.println("No conectado. Error");
            e.printStackTrace();
        }
        
        t.fireTableDataChanged();
        actualizarOrden();
    }//GEN-LAST:event_buttonEditarActionPerformed
    
    private void limpiarFormulario() {
        txtNombreUsuario.setText("");
        txtApellUsuario.setText("");
        txtDni.setText("");
        txtTelfono.setText("");        
    }
    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JButton buttonAñadir;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    private java.awt.TextField txtApellUsuario;
    private java.awt.TextField txtDni;
    private java.awt.TextField txtIdUsuarioRegistro;
    private java.awt.TextField txtNombreUsuario;
    private java.awt.TextField txtTelfono;
    // End of variables declaration//GEN-END:variables
}
